version: '3.1'
services:
  stats-server:
    build: stats/service
    container_name: explore_stat_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_STATS_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - POSTGRES_STATS_USER=postgres
      - POSTGRES_STATS_PASSWORD=iamroot

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-service:
    build: ewm
    container_name: explore_ewm_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_EWM_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - POSTGRES_EWM_USER=postgres
      - POSTGRES_EWM_PASSWORD=iamroot
      - STATS_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
